### ISSUE TITLE
Support for Swift 5.3 and loading Nibs from other Packages.swift

### ISSUE THREAD

**Issue by smamczak** [trafi/NibView#10]
Swift 5.3 allows to add images, string and nibs into Swift package. However, the class is available from Main.bundle but the nib is available only in that package bundle. They created Bundle.module that is generated adhoc and available only as internal property.
In order to load nibs from other packages there must be a way use other bundle than Bundle(for: self)
Please see my #9

**Comment by domasn** [comment]
It has been merged and [tagged](https://github.com/trafi/NibView/releases/tag/2.0.3) 🙌
